<a href="https://colab.research.google.com/github/parknahye-dot/python_study/blob/main/%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [52]:
# 리스트에서 배열 만들기
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

# 2차원 배열
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [35]:
# 0으로 채워진 배열
zeros = np.zeros(5)
print(zeros)  # [0. 0. 0. 0. 0.]

# 1로 채워진 배열
ones = np.ones((3, 4))  # 3행 4열
print(ones)

# 특정 값으로 채우기
full = np.full((2, 3), 7)
print(full)  # 모든 값이 7

# 연속된 숫자 배열
arange = np.arange(0, 10, 2)  # 0부터 10까지 2씩
print(arange)  # [0 2 4 6 8]

# 균등한 간격의 배열
linspace = np.linspace(0, 1, 5)  # 0~1 사이를 5개로
print(linspace)  # [0. 0.25 0.5 0.75 1.]

# 랜덤 배열
random = np.random.rand(3, 3)  # 0~1 사이 랜덤
print(random)

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.18580546 0.17588492 0.22312504]
 [0.95872427 0.56732987 0.48537243]
 [0.47372466 0.36002917 0.69725897]]


In [36]:
# 1부터 10까지 배열
numbers = np.arange(1, 11)
print("1~10:", numbers)

# 5x5 단위 행렬
identity = np.eye(5)
print("단위 행렬:\n", identity)

# 3x4 영행렬
zeros = np.zeros((3, 4))
print("영행렬:\n", zeros)

1~10: [ 1  2  3  4  5  6  7  8  9 10]
단위 행렬:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
영행렬:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# 체스판 패턴 (8x8)
chess = np.zeros((8, 8))
chess[::2, 1::2] = 1  # 짝수 행, 홀수 열
chess[1::2, ::2] = 1  # 홀수 행, 짝수 열
print("체스판:\n", chess)


체스판:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [37]:
# 대각선 배열
diag = np.diag([1, 2, 3, 4, 5])
print("대각 행렬:\n", diag)

# 랜덤 정수 배열 (1~100)
random_int = np.random.randint(1, 101, size=(5, 5))
print("랜덤 배열:\n", random_int)

대각 행렬:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
랜덤 배열:
 [[26 98 50 31 92]
 [ 9 12 45 83 49]
 [76  5 46 79 40]
 [23 29 44  7 55]
 [76 40 11 64  4]]


In [9]:
# 그리드 생성 (좌표 배열)
x = np.linspace(-5, 5, 11)
y = np.linspace(-5, 5, 11)
X, Y = np.meshgrid(x, y)
print(x)
print(y)
print(X)
print(Y)
print("X 좌표:\n", X[:3, :3])  # 일부만 출력
print("Y 좌표:\n", Y[:3, :3])

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
[[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
 [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]]
[[-5. -5. -5. -5. -5. -5. -5. -5. -5. -5. -5.]
 [-4. -4. -4. -4. -4. -4. -4. -4. -4. -4. -4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3. 

In [38]:
distance = np.sqrt(X**2 + Y**2)
print("거리:\n", distance[:3, :3])

거리:
 [[7.07106781 6.40312424 5.83095189]
 [6.40312424 5.65685425 5.        ]
 [5.83095189 5.         4.24264069]]


In [39]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr)
print(arr.shape)   # 배열의 형태, 3행 4열
print(arr.ndim)    # 차원 수, 2차원
print(arr.size)    # 총 요소 개수, 12
print(arr.dtype)   # 데이터 타입, int64

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
12
int64


In [14]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(f"모양: {arr.shape}")
print(f"차원: {arr.ndim}")
print(f"크기: {arr.size}")
print(f"타입: {arr.dtype}")
print(f"바이트 크기: {arr.nbytes}bytes")

모양: (3, 3)
차원: 2
크기: 9
타입: int64
바이트 크기: 72bytes


In [16]:
# 정수 배열
int_arr = np.array([1, 2, 3, 4, 5])
print(f"원본 타입: {int_arr.dtype}")

# 실수로 변환
float_arr = int_arr.astype(np.float64) # .astype(np.float64): float64로 변환
print(f"실수 타입: {float_arr.dtype}")
print(f"값: {float_arr}")

# 불리언으로 변환
bool_arr = int_arr.astype(bool) #0이 아닌 모든 값은 참
print(f"불리언: {bool_arr}")

# 문자열로
str_arr = int_arr.astype(str)
print(f"문자열: {str_arr}, 타입: {str_arr.dtype}")

원본 타입: int64
실수 타입: float64
값: [1. 2. 3. 4. 5.]
불리언: [ True  True  True  True  True]
문자열: ['1' '2' '3' '4' '5'], 타입: <U21


In [17]:
# 다양한 타입의 메모리 사용량 비교
size = 1000000

# 배열 생성 시 데이터 타입 지정
int64_arr = np.arange(size, dtype=np.int64)
int32_arr = np.arange(size, dtype=np.int32)
int16_arr = np.arange(size, dtype=np.int16)
int8_arr = np.arange(size, dtype=np.int8)

print(f"int64: {int64_arr.nbytes / 1024 / 1024:.2f} MB")
print(f"int32: {int32_arr.nbytes / 1024 / 1024:.2f} MB")
print(f"int16: {int16_arr.nbytes / 1024 / 1024:.2f} MB")
print(f"int8: {int8_arr.nbytes / 1024 / 1024:.2f} MB")

# 조건에 따라 적절한 타입 선택
data = np.array([1, 2, 3, 255])

if data.max() < 256:
    optimized = data.astype(np.uint8)  # 0~255
    print(f"최적화: {optimized.dtype}")

int64: 7.63 MB
int32: 3.81 MB
int16: 1.91 MB
int8: 0.95 MB
최적화: uint8


# 원본 (기본 int64)
data = [1, 2, 3, 255]
메모리: 4개 × 8바이트 = 32바이트

# 최적화 (uint8)
optimized = [1, 2, 3, 255]
메모리: 4개 × 1바이트 = 4바이트

절약: 28바이트 (87.5%)

In [18]:
# arr[start:stop:step]

arr = np.array([10, 20, 30, 40, 50])

# arr[index]
print(arr[0])      # 10 (첫 번째)

# arr[negative_index]
print(arr[-1])     # 50 (마지막)

# arr[start:stop]
print(arr[1:4])    # [20 30 40], 인덱스 1, 2, 3 (4는 제외!)

# arr[start:stop:step]
print(arr[::2])    # [10 30 50] (2칸씩)

10
50
[20 30 40]
[10 30 50]


In [19]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# 특정 요소 접근 [행, 열]
print(arr_2d[0, 0])     # 1
print(arr_2d[1, 2])     # 7
print(arr_2d[-1, -1])   # 12

# 행 전체 선택
print(arr_2d[0])        # [1 2 3 4]
print(arr_2d[0, :])     # 위와 동일

# 열 전체 선택
print(arr_2d[:, 0])     # [1 5 9] (첫 번째 열)
print(arr_2d[:, 1])     # [2 6 10] (두 번째 열)

# 부분 선택
print(arr_2d[0:2, 1:3])  # 0~1행, 1~2열

1
7
12
[1 2 3 4]
[1 2 3 4]
[1 5 9]
[ 2  6 10]
[[2 3]
 [6 7]]


In [20]:
arr = np.arange(1, 21)  # 1~20

print("원본:", arr)
print("앞 5개:", arr[:5])
print("뒤 5개:", arr[-5:])
print("중간 10개:", arr[5:15])
print("홀수 인덱스:", arr[1::2])
print("역순:", arr[::-1])

원본: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
앞 5개: [1 2 3 4 5]
뒤 5개: [16 17 18 19 20]
중간 10개: [ 6  7  8  9 10 11 12 13 14 15]
홀수 인덱스: [ 2  4  6  8 10 12 14 16 18 20]
역순: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [22]:
# 5x5 배열 생성
arr = np.arange(1, 26).reshape(5, 5)
print("전체:\n", arr)

전체:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [23]:
print("\n첫 2행:", arr[:2])


첫 2행: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
print("\n마지막 2열:\n", arr[:, -2:])


마지막 2열:
 [[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [25]:
print("\n중앙 3x3:\n", arr[1:4, 1:4])


중앙 3x3:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [28]:
print("\n대각선:", np.diag(arr))
print("\n역대각선:", np.diag(np.fliplr(arr)))


대각선: [ 1  7 13 19 25]

역대각선: [ 5  9 13 17 21]


In [29]:
border = np.concatenate([
    arr[0, :],      # 첫 행
    arr[-1, :],     # 마지막 행
    arr[1:-1, 0],   # 첫 열 (모서리 제외)
    arr[1:-1, -1]   # 마지막 열 (모서리 제외)]
    ])
print("\n테두리:", border)


테두리: [ 1  2  3  4  5 21 22 23 24 25  6 11 16 10 15 20]


In [32]:
arr = np.arange(0, 100, 10)
print("배열:", arr)

# 특정 인덱스들만 선택
indices = [1, 3, 5, 7]
selected = arr[indices]
print("선택:", selected)

배열: [ 0 10 20 30 40 50 60 70 80 90]
선택: [10 30 50 70]


In [33]:
# 2차원에서 특정 좌표들 선택
arr_2d = np.arange(1, 26).reshape(5, 5)

rows = [0, 1, 2]
cols = [0, 2, 4]
values = arr_2d[rows, cols]
print("\n대각선 값:", values)


대각선 값: [ 1  8 15]


In [34]:
# 조건부 인덱싱 (불리언 마스크)
arr = np.random.randint(1, 100, 20)
print("\n원본:", arr)
print("50 이상:", arr[arr >= 50]) # 50보다 큰 수 출력
print("짝수:", arr[arr % 2 == 0])
print("30~70:", arr[(arr >= 30) & (arr <= 70)])


원본: [72 60 48 26 48 30 22 46 79 73 94 51 46 53 51 54 87 63 52 14]
50 이상: [72 60 79 73 94 51 53 51 54 87 63 52]
짝수: [72 60 48 26 48 30 22 46 94 46 54 52 14]
30~70: [60 48 48 30 46 51 46 53 51 54 63 52]


In [40]:
# 크기가 안 맞으면 기본적으로 에러!
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

# 배열끼리 연산
print(arr1 + arr2)   # [11 22 33 44]
print(arr1 * arr2)   # [10 40 90 160]
print(arr2 / arr1)   # [10. 10. 10. 10.]

# 스칼라 연산
print(arr1 + 10)     # [11 12 13 14]
print(arr1 * 2)      # [2 4 6 8]
print(arr1 ** 2)     # [1 4 9 16]

[11 22 33 44]
[ 10  40  90 160]
[10. 10. 10. 10.]
[11 12 13 14]
[2 4 6 8]
[ 1  4  9 16]


In [41]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 각 행에 [10, 20, 30] 더하기, 확장
print(arr + np.array([10, 20, 30]))

# 각 열에 100 더하기
print(arr + 100)

[[11 22 33]
 [14 25 36]
 [17 28 39]]
[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [42]:
arr = np.array([1, 2, 3])  # (3,)
arr + 10
# 10이 [10, 10, 10]으로 확장
# [11 12 13] ✓

array([11, 12, 13])

In [ ]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])    # (2, 3)
arr2 = np.array([10, 20, 30])   # (3,)

arr1 + arr2

# arr2가 [[10, 20, 30],
#        [10, 20, 30]]로 확장

# 결과: [[11 22 33]
#       [14 25 36]] ✓

In [ ]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])    # (2, 3)
arr2 = np.array([[10],
                 [20]])         # (2, 1)

arr1 + arr2

# arr2가 [[10, 10, 10],
#        [20, 20, 20]]로 확장

# 결과: [[11 12 13]
#       [24 25 26]] ✓

(3,)    + (3,)    → ✓ 같은 크기

(2, 3)  + (3,)    → ✓ (3,)이 (1, 3)으로 해석 후 확장

(2, 3)  + (2, 1)  → ✓ (2, 1)이 (2, 3)으로 확장

(3,)    + (4,)    → ❌ 맞출 수 없음

(2, 3)  + (2, 4)  → ❌ 마지막 차원이 다름

In [ ]:
# 두 벡터 연산
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print("덧셈:", v1 + v2)
print("뺄셈:", v1 - v2)
print("곱셈:", v1 * v2)
print("나눗셈:", v2 / v1)

# 내적 (dot product)
dot = np.dot(v1, v2) # 1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32
print(f"내적: {dot}")

# 벡터 크기 계산
'''
linalg: Linear Algebra (선형대수)
norm: 노름(Norm), 벡터의 길이/크기 측정
'''
magnitude = np.linalg.norm(v1) # 각 요소를 제곱하고, 합한 후, 루트
print(f"v1 크기: {magnitude:.2f}")

# 행렬 곱셈 (2차원)
A = np.array([[1, 2],
              [3, 4]])  # (2, 2)

B = np.array([[5, 6],
              [7, 8]])  # (2, 2)

print(np.dot(A, B))
'''
[[1*5+2*7  1*6+2*8]     [[19 22]
[3*5+4*7  3*6+4*8]]  =  [43 50]]
'''

### 계산 과정
'''
A의 1행 · B의 1열 = 1*5 + 2*7 = 19
A의 1행 · B의 2열 = 1*6 + 2*8 = 22
A의 2행 · B의 1열 = 3*5 + 4*7 = 43
A의 2행 · B의 2열 = 3*6 + 4*8 = 50
'''

In [43]:
# 두 행렬
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# 요소별 곱셈
element_wise = A * B
print("요소별 곱셈:\n", element_wise)

# 행렬 곱셈
matrix_mult = np.dot(A, B)  # 또는 A @ B
# [[1*5+2*7  1*6+2*8]     [[19 22]
#  [3*5+4*7  3*6+4*8]]  =  [43 50]]
print("\n행렬 곱셈:\n", matrix_mult)

# 전치
print("\nA 전치:\n", A.T)

# 역행렬
A_inv = np.linalg.inv(A)
print("\nA 역행렬:\n", A_inv)

# 검증: A * A^(-1) = I
identity = np.dot(A, A_inv)
print("\nA * A^(-1):\n", np.round(identity, 2))

요소별 곱셈:
 [[ 5 12]
 [21 32]]

행렬 곱셈:
 [[19 22]
 [43 50]]

A 전치:
 [[1 3]
 [2 4]]

A 역행렬:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A * A^(-1):
 [[1. 0.]
 [0. 1.]]


In [44]:
# 간단한 이미지를 행렬로 표현 (3x3 grayscale)
image = np.array([[100, 150, 200],
                  [120, 180, 220],
                  [140, 190, 240]])
print("원본:\n", image)

# 밝기 조정 (+50)
brighter = np.clip(image + 50, 0, 255)
'''
np.clip(배열, 최솟값, 최댓값)
배열의 값을 특정 범위로 제한
최솟값보다 작으면 → 최솟값으로
최댓값보다 크면 → 최댓값으로
'''
print("\n밝게:\n", brighter)

# 명암 조정 (대비 증가)
contrast = np.clip((image - 128) * 1.5 + 128, 0, 255)
print("\n대비:\n", contrast.astype(int))

# 흑백 반전
inverted = 255 - image
print("\n반전:\n", inverted)

# 블러 효과 (간단한 평균 필터)
padded = np.pad(image, 1, mode='edge')
blurred = np.zeros_like(image)
for i in range(image.shape[0]):
    for j in range(image.shape[1]):
        kernel = padded[i:i+3, j:j+3]
        blurred[i, j] = kernel.mean()

print("\n블러:\n", blurred.astype(int))

원본:
 [[100 150 200]
 [120 180 220]
 [140 190 240]]

밝게:
 [[150 200 250]
 [170 230 255]
 [190 240 255]]

대비:
 [[ 86 161 236]
 [116 206 255]
 [146 221 255]]

반전:
 [[155 105  55]
 [135  75  35]
 [115  65  15]]

블러:
 [[124 157 191]
 [137 171 204]
 [151 184 217]]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(np.sum(arr))      # 55 (합계)
print(np.mean(arr))     # 5.5 (평균)
print(np.max(arr))      # 10 (최대)
print(np.min(arr))      # 1 (최소)
print(np.std(arr))      # 2.87... (표준편차)

# 메서드로도 가능
print(arr.sum())
print(arr.mean())
print(arr.max())

55
5.5
10
1
2.8722813232690143
55
5.5
10


In [46]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# axis=0: 세로 방향 (열 기준)
print(arr_2d.sum(axis=0))  # [12 15 18]

# axis=1: 가로 방향 (행 기준)
print(arr_2d.sum(axis=1))  # [6 15 24]

# axis 없으면 전체
print(arr_2d.sum())  # 45

[12 15 18]
[ 6 15 24]
45


In [49]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

arr_2d.sum(axis=0)    # [5 7 9] - 열 합계
arr_2d.mean(axis=0)   # [2.5 3.5 4.5] - 열 평균
arr_2d.std(axis=0)    # [1.5 1.5 1.5] - 열 표준편차
arr_2d.var(axis=0)    # [2.25 2.25 2.25] - 열 분산
arr_2d.min(axis=0)    # [1 2 3] - 열 최솟값
arr_2d.max(axis=0)    # [4 5 6] - 열 최댓값

array([4, 5, 6])

In [ ]:
arr_2d.argmin(axis=0) # [0 0 0] - 최솟값의 인덱스
arr_2d.argmax(axis=0) # [1 1 1] - 최댓값의 인덱스
arr_2d.sort(axis=0)   # 각 열을 정렬

In [ ]:
arr_2d.cumsum(axis=0) # [[1 2 3]    - 누적 합
                      #  [5 7 9]]
arr_2d.cumprod(axis=0) # [[1  2  3]  - 누적 곱
                       #  [4 10 18]]

In [ ]:
arr_2d.prod(axis=0)   # [4 10 18] - 열 곱
arr_2d.median(axis=0) # [2.5 3.5 4.5] - 열 중앙값 (np.median 사용)
arr_2d.any(axis=0)    # [True True True] - 하나라도 True인지
arr_2d.all(axis=0)    # [True True True] - 모두 True인지

In [ ]:
arr_2d.sum(axis=0)    # [5 7 9] - 열 합계
arr_2d.mean(axis=0)   # [2.5 3.5 4.5] - 열 평균
arr_2d.std(axis=0)    # [1.5 1.5 1.5] - 열 표준편차
arr_2d.var(axis=0)    # [2.25 2.25 2.25] - 열 분산
arr_2d.min(axis=0)    # [1 2 3] - 열 최솟값
arr_2d.max(axis=0)    # [4 5 6] - 열 최댓값

- axis=0: 세로로 내려가며 계산 (열별 합)
- axis=1: 가로로 가며 계산 (행별 합)

In [50]:
# 1~24 배열을 다양한 모양으로
arr = np.arange(1, 25)

print("1차원:", arr)
print("\n2x12:\n", arr.reshape(2, 12))
print("\n4x6:\n", arr.reshape(4, 6))
print("\n3x8:\n", arr.reshape(3, 8))
print("\n2x3x4:\n", arr.reshape(2, 3, 4))

1차원: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

2x12:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]

4x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

3x8:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]

2x3x4:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [51]:
# 학생 데이터 (점수, 출석률)
scores = np.array([85, 92, 78, 90, 88, 76, 95, 89, 82, 91])
attendance = np.array([95, 90, 85, 100, 88, 70, 95, 92, 80, 98])
print("점수:", scores)
print("출석률:", attendance)

# 조건: 점수 85점 이상 AND 출석률 90% 이상
condition = (scores >= 85) & (attendance >= 90)
excellent = scores[condition]
print(f"\n우수 학생 점수: {excellent}")
print(f"우수 학생 수: {excellent.size}명")

# where 사용 (조건에 따라 다른 값)
# np.where(조건, 참일 때 값, 거짓일 때 값)
grade = np.where(scores >= 90, 'A',
         np.where(scores >= 80, 'B',
         np.where(scores >= 70, 'C', 'F')))
print(f"\n학점: {grade}")

# 점수 상위 30%
# 데이터를 크기 순으로 정렬했을 때, 하위 n%에 해당하는 값
percentile_70 = np.percentile(scores, 70)
top_30 = scores[scores >= percentile_70]
print(f"\n상위 30%: {top_30}")

# 조건별 집계
print(f"\nA학점 평균: {scores[grade == 'A'].mean():.1f}")
print(f"B학점 평균: {scores[grade == 'B'].mean():.1f}")

점수: [85 92 78 90 88 76 95 89 82 91]
출석률: [ 95  90  85 100  88  70  95  92  80  98]

우수 학생 점수: [85 92 90 95 89 91]
우수 학생 수: 6명

학점: ['B' 'A' 'C' 'A' 'B' 'C' 'A' 'B' 'B' 'A']

상위 30%: [92 95 91]

A학점 평균: 92.0
B학점 평균: 86.0


# Section 1: NumPy 기초 (1시간)

## 문제 1-1: 배열 생성 연습

다음 배열들을 만드세요:
1. 1부터 20까지의 배열
2. 0으로 채워진 3x4 배열
3. 1로 채워진 5x5 배열
4. 10으로 채워진 2x3 배열

In [59]:
numbers = np.arange(1, 21)
print("1.:", numbers)

zeros = np.zeros((3, 4))
print("2.", zeros)

one = np.full((5, 5), 1)
print("3.", one)

ten = np.full((2, 3), 10)
print("4.", ten)

1.: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2. [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
3. [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
4. [[10 10 10]
 [10 10 10]]


## 문제 1-2: 배열 인덱싱

다음 배열에서:

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
```

1. 첫 번째 행 출력
2. 마지막 열 출력
3. 7이라는 값 출력
4. 2행 2열부터 3행 3열까지 출력

In [113]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("1.", arr[0])
print("2.", arr[:, -1])
print("3.", arr[1, 2])
print("4.", arr[1:3, 1:3])

1. [1 2 3 4]
2. [ 4  8 12]
3. 7
4. [[ 6  7]
 [10 11]]


## 문제 1-3: 배열 연산

두 배열을 만들고 연산하세요:

In [82]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# 1. 두 배열의 합
# 2. 두 배열의 곱
# 3. arr1의 각 요소에 10을 더하기
# 4. arr2의 각 요소를 2로 나누기

print("1.", arr1 + arr2)
print("2.", arr1 * arr2)
print("3.", arr1 +10)
print("4.", arr2 / 2)

1. [11 22 33 44 55]
2. [ 10  40  90 160 250]
3. [11 12 13 14 15]
4. [ 5. 10. 15. 20. 25.]


## 문제 1-4: 집계 함수

다음 배열의 통계를 구하세요:

In [86]:
scores = np.array([85, 92, 78, 90, 88, 76, 95, 89])

# 1. 평균
# 2. 최고점
# 3. 최저점
# 4. 표준편차
# 5. 총점

print("1.평균:", np.mean(scores))
print("2.최고점:", np.max(scores))
print("3.최저점:", np.min(scores))
print("4.표준편차:", np.std(scores))
print("5.총점:", np.sum(scores))

1.평균: 86.625
2.최고점: 95
3.최저점: 76
4.표준편차: 6.203577596838779
5.총점: 693


## 문제 1-5: 2차원 배열 집계

다음 배열에서:

In [92]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# 1. 각 행의 합 (axis=1)
# 2. 각 열의 평균 (axis=0)
# 3. 전체 합

print("1. 각 행의 합", data.sum(axis=1))
print("2. 각 열의 평균", data.mean(axis=0))
print("3. 전체 합", data.sum())

1. 각 행의 합 [ 6 15 24]
2. 각 열의 평균 [4. 5. 6.]
3. 전체 합 45


문제 1-6: 배열 reshape

In [97]:
arr = np.arange(24)

# 0부터 23까지
# 1. 4행 6열로 변환
# 2. 3행 8열로 변환
# 3. 2행 3행 4열로 변환 (3차원)

print("1. 0~23:", arr)

arr46 = arr.reshape(4,6)
print("2. 4행 6열:", arr46)

arr38 = arr.reshape(3, 8)
print("3. 3행 8열:", arr38)

arr234 = arr.reshape(2, 3, 4)
print("4. 2면 3행 4열:", arr234)

1. 0~23: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2. 4행 6열: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
3. 3행 8열: [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
4. 2행 3행 4열: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


문제 1-7: 조건 필터링

In [130]:
data = np.array([15, 23, 8, 42, 16, 30, 7, 19, 25, 31])

# 1. 20 이상인 값만 출력
# 2. 10 이하인 값만 출력
# 3. 15와 25 사이의 값만 출력

print("1. 20이상:", data[data > 20])
print("1. 10이하:", data[data < 10])
print("1. 15~25:", data[(data>15)&(data<25)])

1. 20이상: [23 42 30 25 31]
1. 10이하: [8 7]
1. 15~25: [23 16 19]


# Section 2: NumPy 응용 (1시간)

## 문제 2-1: 성적 데이터 분석

5명의 학생이 3과목 시험을 봤습니다:

In [115]:
scores = np.array([[85, 90, 78],   # 학생1
                   [92, 88, 95],   # 학생2
                   [78, 82, 80],   # 학생3
                   [88, 85, 90],   # 학생4
                   [95, 92, 98]])  # 학생5

# 1. 각 학생의 평균 점수
# 2. 각 과목의 평균 점수
# 3. 전체 평균
# 4. 가장 높은 점수
# 5. 평균이 가장 높은 학생은? (인덱스 출력)

scores1 = np.mean(scores, axis=1)
print("1. 각 학생의 평균 점수", scores1)
scores2 = np.mean(scores, axis=0)
print("2. 각 과목의 평균 점수", scores2)
scores3 = np.mean(scores)
print("3. 전체 평균", scores3)
scores4 = np.max(scores)
print("4. 가장 높은 점수", scores4)
scores5 = np.argmax(scores1)
print("5. 평균이 가장 높은 학생:", scores5)

1. 각 학생의 평균 점수 [84.33333333 91.66666667 80.         87.66666667 95.        ]
2. 각 과목의 평균 점수 [87.6 87.4 88.2]
3. 전체 평균 87.73333333333333
4. 가장 높은 점수 98
5. 평균이 가장 높은 학생: 4


## 문제 2-2: 온도 데이터 변환

화씨 온도를 섭씨로 변환하세요 (C = (F - 32) × 5/9):

In [116]:
fahrenheit = np.array([32, 68, 86, 104, 122])

# 섭씨로 변환
celsius = (fahrenheit - 32) * 5 / 9

print(celsius)

[ 0. 20. 30. 40. 50.]


## 문제 2-3: 행렬 곱셈

두 행렬을 곱하세요:

In [117]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# 행렬 곱셈 (dot product)
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


문제 2-4: 랜덤 데이터 생성 및 분석

In [128]:
# 1. 0~100 사이 랜덤 정수 30개 생성
data = np.random.randint(0, 101, 30)

# 2. 5행 6열로 변환
data_2d = data.reshape(5, 6)

# 3. 50 이상인 값들의 평균
high_values = data_2d[data_2d >= 50].mean()
print(data_2d)
print(f"50 이상 값들의 평균: {high_values}")

[[18 15 40 52 49 74]
 [46 60 74 38 48 91]
 [30 66 36 35 19 37]
 [81 35  6 76 40 97]
 [69 80 41 21 19 67]]
50 이상 값들의 평균: 73.91666666666667


## 문제 2-5: 데이터 정규화 (스케일링)

데이터를 0~1 사이로 변환하세요 (Min-Max Scaling):

공식: (x - min) / (max - min)

In [129]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# 정규화
normalized = (data - data.min()) / (data.max() - data.min())
print(normalized)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')